version: '3.1'

services:

  bot:
    build: ./bot
    restart: always
    environment:
      API_TOKEN: "5792605370:AAHH5pdOxnhumdC90LKJo_meooKGuoKajgo"
      DJANGO_DB_USER: django_user
      DJANGO_DB_NAME: django_db
      DJANGO_DB_PASSWORD: p@ssword
      DJANGO_DB_PORT: 5432

  bot-sender:
    build: ./bot-sender
    ports:
      - 8082:8082
    restart: always
    environment:
      API_TOKEN: "5792605370:AAHH5pdOxnhumdC90LKJo_meooKGuoKajgo"
    
  db:
    build: ./postgres-db
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssword
      # Creds for django_db 
      DJANGO_DB_USER: django_user
      DJANGO_DB_NAME: django_db
      DJANGO_DB_PASSWORD: p@ssword
    volumes:
      - "./postgres-db/db-config:/docker-entrypoint-initdb.d/"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]

  python-seed:
    build: ./python-seed
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_USER: django_user
      DB_NAME: django_db
      DB_PASSWORD: p@ssword
      DB_PORT: 5432

  web:
    build: ./simplewebapp
    ports:
      - 8081:8081
    restart: always
    environment:
      DJANGO_DB_USER: django_user
      DJANGO_DB_NAME: django_db
      DJANGO_DB_PASSWORD: p@ssword
      DJANGO_DB_PORT: 5432
      DJANGO_ADMIN_USER: admin
      DJANGO_ADMIN_MAIL: admin@admin.com
      DJANGO_ADMIN_PASSWORD: "!Q1w2e3r4"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:8081" ]
        interval: 30s
        timeout: 10s
        retries: 5