# Generated by Django 4.1.1 on 2022-09-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabinet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='message_id',
            field=models.BigIntegerField(),
        ),
    ]
