version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssword
      APP_DB_USER: db_user
      APP_DB_PASS: password
      APP_DB_NAME: db
    ports:
      - "5432:5432"
    volumes:
      - "./db-config:/docker-entrypoint-initdb.d/"
      - "./my-postgres.conf:/etc/postresql/postgresql.conf"
   
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    environment: 
      PGADMIN_DEFAULT_EMAIL: "test@test.com"
      PGADMIN_DEFAULT_PASSWORD: "123123123"
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: "True"
  